exercisedjango/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<id>/', views.show, name='show'),


]

exercisedjango/exercisedjango/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

handler404 = 'exercisedjango.views.handler404'
handler500 = 'exercisedjango.views.handler500'
urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('blog/', include('blog.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

exercisedjango/blog/models.py
from django.db import models
class TimespamModel(models.Model):
        created_at = models.DateTimeField(auto_now_add=True) 
        updated_at = models.DateTimeField(auto_now=True) 

        class Meta:
            abstract = True


class Post(TimespamModel):

    title = models.CharField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return self.title

exercisedjango/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
# from .mocks import Post
from .models import Post

def index(request):
    posts = Post.objects.all()
    return render(request, 'blog/index.html', {'posts': posts})


def show(request, id):
    post = get_object_or_404(Post, pk=id)
    #(version plus longue que get_object_or_404)  try:
    #     post = Post.objects.get(pk=id)
    # except Post.DoesNotExist:
    #     raise Http404('Sorry, post #{} not found.'.format(id))
    return render(request, 'blog/show.html', {'post': post})

exercisedjango/exercisedjango/views.py
from django.shortcuts import render


def home(request):

    return render(request, 'pages/home.html')


def about(request):

    return render(request, 'pages/about.html')


def contact(request):

    return render(request, 'pages/contact.html')


def handler404(request, exception):

    return render(request, 'error/404.html', {'error': exception}, status=404)


def handler500(request, exception=None):

    return render(request, 'error/500.html', {}, status=500)

    # pass
# on mets passe quand on ne sait pas encore quoi mettre dans notre fonction

exercisedjango/blog/templates/blog/index.html
{% extends 'layouts/base.html' %} 

{% block title %} 
Blog 
{% endblock title %}


{%block content %}
<h1>Blog ({{posts|length}} posts)</h1>

{% for posts in posts%}


<article class=article_blog>
  <h2>
    <a href="{% url 'blog:show' posts.id%}"
      >#{{posts.id}} - {{posts.title|upper}}</a
    >
  </h2>
  <p>{{posts.body|truncatewords:3}}</p>
  <p><a href="{% url 'blog:show' posts.id%}">lire la suite</a></p>
</article>

{% if not forloop.last %}
<hr />

{% endif %} {%empty%}
<p>Sorry, no posts avaible.</p>
{% endfor %} 

{% endblock content %}

exercisedjango/blog/templates/blog/show.html
{% extends 'layouts/base.html' %} 

{% block title %} 
Blog | 
{{post.title}} 
{%endblock title %} 

{% block content %}

<article>
  <h1>#{{post.id}} - {{post.title}}</h1>
  <p>{{post.body}}</p>
</article>
<hr />

<p><a href="{% url 'blog:index' %}">👈 All post</a></p>

{% endblock content %}

exercisedjango/templates/layouts/_footer.html
<footer>
    <p>&copy; Copyright {%now 'Y'%} &middo ExerciseDjango &middo rights reserved ! </p>
</footer>

exercisedjango/templates/layouts/_nav.html
<nav class='navbar'>
  <h2 class='title' href="#">Exercise Django</h2>
  
  <ul class='navbar_right'>
    <li><a class='nav_a' href="{% url 'home' %}">Home</a></li>
    <li><a class='nav_a' href="{% url 'blog:index' %}">Blog</a></li>
    <li><a class='nav_a' href="{% url 'about' %}">About</a></li>
    <li><a class='nav_a' href="{% url 'contact' %}">Contact</a></li>
  </ul>

</nav>

exercisedjango/templates/layouts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Exercice Django {% endblock %}</title>
  </head>
  <body>
    {% include 'layouts/_nav.html' %} 
    {% block content %} {% endblock content %}
    {% include 'layouts/_footer.html' %} 
  </body>
</html>

exercisedjango/templates/pages/about.html
{% extends 'layouts/base.html' %}

{% block title %}
    About us
{% endblock title %}

{% block content %}
<h1>About us</h1>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque mollitia
repellendus aut repudiandae animi vitae exercitationem ratione atque odio! Fugit
ipsam exercitationem quidem. Numquam, inventore tempora ipsa, velit incidunt
illo culpa magnam sed doloremque quis fugit maiores possimus quae ratione. 
{%endblock content %}

exercisedjango/templates/pages/contact.html
{% extends 'layouts/base.html' %} 
{% block title %} 

Contact 

{% endblock title %}

{% block content %}

<h1>Contact</h1>
Lorem ipsum dolor sit, amet consectetur adipisicing elit. Explicabo tempore
nostrum ullam enim reiciendis itaque, provident accusantium porro laborum vitae
rerum fuga at ipsam ipsa architecto corporis nulla soluta voluptas. Esse non
officiis illum nemo odio perspiciatis, molestias suscipit ullam. 

{% endblock content %}

exercisedjango/templates/pages/home.html
{% extends 'layouts/base.html' %} 

{% block title %} 

Homepage 

{% endblock title%} 


{% block content %}

<h1>Hello !</h1>

<a href="{% url 'blog:index' %}">Visiter notre blog</a>

{% endblock content %}